AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  soundcloud
  
Globals:
  Function:
    Timeout: 6000

Resources:
  DefaultRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DefaultRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  PlaylistBackupFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: playlist-backup/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Role:
        Fn::GetAtt:
          - DefaultRole
          - Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)